### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by theBest3000** [GreenPassApp/greenpass-app#1]
Tested at 12:06 but 10:06 is displayed. Maybe missing UTC +2?
![473-1024](https://user-images.githubusercontent.com/44313069/124280500-0a7d2000-db49-11eb-9139-cd2c7ac681da.jpg)

**Comment by bmiklautz** [comment]
I have observed the same issue. Just decoded the certificate and the time is, as @theBest3000 assumed, in UTC
```
'sc': '2021-07-02T07:31:02Z',
```
Would be nice if this could be displayed as local time.

**Comment by JakobStadlhuber** [comment]
Thank you we will also fix this issue this weekend. Thanks for sharing it with us.
