### ISSUE TITLE
Make status "vaccination", "test" or "recovery" optional

### ISSUE THREAD

**Issue by hannesfrater** [GreenPassApp/greenpass-app#10]
Hey,
Great app, much better than the official BRZ app. However one feature is better and more privacy friendly in the official app (see screenshot below): the status "vaccination", "test" or "recovery" is not displayed by default. 

I personally do not care if the status is display or not and I think it's a great optional feature. However there should be an option to hide/show the status based on the user preference.

Screenshot official app:

![screenshot](https://user-images.githubusercontent.com/83874394/124473390-8cff1d00-dd9f-11eb-9ed5-6987f4e75541.jpg)

Screenshot  greenpass app:
![headvisual](https://user-images.githubusercontent.com/83874394/124474404-c5ebc180-dda0-11eb-9dd6-ae1c04e406dd.png)

**Comment by kevinhaendel** [comment]
This feature was already added in 958c0efab363b867f29f7fd3050bbcc928f5393c
