### ISSUE TITLE
Colour Set German Specification

### ISSUE THREAD

**Issue by WillTheGeek** [GreenPassApp/greenpass-app#12]
Following "issue": "tested negative" shows up as red under the German specification, while showing blue (EU) and green (Austria). In your press documents, you show a red screen also for an error. Would it not be natural to use the red colour for "dangerous" situations, while keeping the colour for "tested negative" green?

**Comment by ThomasKoppensteiner** [comment]
Maybe this behaviour is related to #5. Which version of the app did you use?

**Comment by WillTheGeek** [comment]
Same, but I feel still somewhat different. These tests (PCR) only show the red/"invalid" screen in the German specification, while Europe and Austria show these tests as green. The rapid tests are shown as green in all three specifications.
App version: 1.0.1 (for Android from the Play Store).

**Comment by JakobStadlhuber** [comment]
I hope I understood the question correctly but the colors are supposed to represent the regulations. Red reflects that for example the test does not comply with the current regulations in, for example Austria.If it is green it corresponds to the correct regulations and blue is only the case if the EU is selected, thats the generic version without color representation.
