### ISSUE TITLE
Switch to English

### ISSUE THREAD

**Issue by timbuktu-t** [GreenPassApp/greenpass-app#14]
Nice work! A way to switch everything to english would be helpful tough, e.g. when travelling across Europe.

**Comment by ThomasKoppensteiner** [comment]
https://lingohub.com/ could be handy for translations

**Comment by JakobStadlhuber** [comment]
Is already implemented and was already pushed to google.
Unfortunately we have other problems currently: https://www.derstandard.at/story/2000128017918/gruener-pass-alternative-app-der-fh-hagenberg-aus-google-play

But we will be back soon also with this feature.

**Comment by JakobStadlhuber** [comment]
> https://lingohub.com/ could be handy for translations

https://crowdin.com/project/greenpass
