### ISSUE TITLE
Non-OSS dependencies block F-Droid inclusion

### ISSUE THREAD

**Issue by pludi** [GreenPassApp/greenpass-app#16]
As noted in https://github.com/GreenPassApp/greenpass-app/issues/4#issuecomment-876174468 there is some dependency in the code that prevents the F-Droid build from completing as it includes blocklisted packages, probably from the `com.google.android.gms` namespace.

`gradle -q dependencies` unfortunately doesn't give any detailed information on my machine.

One possible source could be the included Google ML package which I assume is used for QR code detection & decoding, but I don't know enough about the code to verify and/or change that.

**Comment by JakobStadlhuber** [comment]
Yes you are right, Google ML, which works offline without communication to google, will not be accepted from F-Drod.
For now please use the .apk https://greenpassapp.eu/download

**Comment by jondo** [comment]
Was this closed as "wontfix" or as "fixed"?
