### ISSUE TITLE
Using logic from eu-digital-green-certificates to validate QR-Codes

### ISSUE THREAD

**Issue by SandroBerger** [GreenPassApp/greenpass-app#18]
Just as an idea, wouldn't it be better to validate QR-Codes with the logic from https://github.com/eu-digital-green-certificates as it is a service provided by the EU and therefore (hopefully) always has the latest regulations configured for every country? By doing so the validation would not rely on a static configuration like https://github.com/GreenPassApp/greenpass-app/blob/cb7ba30cfd0bcb8fc90e38b31fde634a702266c7/lib/local_storage/country_regulations/regulations_provider.dart#L15 where the duration is maintained manually in the JSON file for every country.

* https://github.com/eu-digital-green-certificates/dgca-verifier-app-android
* https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios

The issue can be closed; Just wanted to mention it as an idea. :smiley:

**Comment by JakobStadlhuber** [comment]
Unfortunately, only entry information are in this database.
