### ISSUE TITLE
Different error messages for invalid and expired tests/vaccinations

### ISSUE THREAD

**Issue by bauxi** [GreenPassApp/greenpass-app#19]
Currently when an expired test result is scanned by the app, it only shows the user that the result is invalid (ungültig). However, in order to make it clearer for the user, some kind of more detailled error explanation would be best. To inform the user whether the test or the vaccination status has expired. And only if the certificate signature cannot be verified print something like: "This certificate is invalid. This might be a fraud attempt." 

The reason for my suggestion is that most users might think, if the error message is really generic that there is something wrong with the app and not with the scanned code.

**Comment by JakobStadlhuber** [comment]
A generic answer was intentionally used because of privacy reasons, it is not necessary for a person that scans a certificate to know this.
