### ISSUE TITLE
Show how long certificate is valid

### ISSUE THREAD

**Issue by libexus** [GreenPassApp/greenpass-app#20]
It would be cool to see when a certificate gets valid (i.e. vaccination) and when invalid (i.e. Corona test)

(Btw thanks for the cool app; let's hope it gets back to playstore soon)

**Comment by hb02** [comment]
I would like to mention PullRequest #8

**Comment by libexus** [comment]
Yeah, I've also just noticed, but it seems like the maintainers haven't seen this yet. Maybe @Pinging them will help?

**Comment by JakobStadlhuber** [comment]
Fixed in new the new version
