### ISSUE TITLE
Vaccine type is "Other" 

### ISSUE THREAD

**Issue by 10Meisterbaelle** [GreenPassApp/greenpass-app#25]
The vaccine type shows up as "Other", even though I'm vaccinated with an mRNA vaccine. This only happens (from my testing) with Austrian certificates, not with German certificates

**Comment by 10Meisterbaelle** [comment]
Austrian certificates don't seem to contain that data, so I would recommend just hiding it for these certificates.

**Comment by JakobStadlhuber** [comment]
Fixed in the new version
