### ISSUE TITLE
In Germany, my PCR Test shows as invalid even though it is valid

### ISSUE THREAD

**Issue by 10Meisterbaelle** [GreenPassApp/greenpass-app#28]
![Screenshot_20210819-165316_GreenPass~2.png](https://user-images.githubusercontent.com/45918080/130091465-517625d9-e0bb-4cd8-96ad-63ff148460e3.png)
It seems to only show a PCR test as valid if it's not older than 24h. This might be because different states in Germany have different rules regarding to tests.

**Comment by Ein-Tim** [comment]
Same as #27?

**Comment by JakobStadlhuber** [comment]
Still an issue with new version?

**Comment by 10Meisterbaelle** [comment]
> Same as #27?

Yes, I'm closing the issue
