### ISSUE TITLE
GreenPass v1.1.1 does not show the pass without internet connection

### ISSUE THREAD

**Issue by sphh** [GreenPassApp/greenpass-app#29]
I downloaded and installed v1.1.1 from github.

When I start it for the first time, it takes approx. 5s to get from the start screen to the `Welcome!` wizard.

I add my QR code to the app. It is displayed.

I close the app and open it again. The app is stuck at the start screen (showing `GreenPass` and the Red Cross logo). Whatever I do it does not show my QR code.

Perhaps it's worth noting, that `GreenPass` does not have access to the internet. (I run Android 8.1)

What do I have to do, to get `GreenPass` to show my vaccination status?

**Comment by sphh** [comment]
By accident, I found out, how to display my pass:
1. Start `GreenPass`.
2. Lock the phone.
3. Wake the phone up and unlock it.
4. The pass is shown.

This works reliably, but is a bit clumsy.

**Comment by sphh** [comment]
Just found another way to get it working: Enable internet access for the app!

This supports my first suspicion, that the disabled internet access is the culprit. Please could you add the possibility, that it can work without internet access. Then there should be an option, which gives you the possibility to disable the automatic check for updates. Obviously there should then be a way to check manually. Thanks.

**Comment by JakobStadlhuber** [comment]
Should be fixed in the new version, if not please reopen the issue.

**Comment by sphh** [comment]
Danke Jakob!
