### ISSUE TITLE
Shared Link to "Recovered" certificate shows the wrong date

### ISSUE THREAD

**Issue by Platti** [GreenPassApp/greenpass-app#3]
The certificate is valid when scanned but wrong when shared via link.
True date: 22.04.2021

![Screenshot_20210702-192303](https://user-images.githubusercontent.com/11665458/124309599-3f01d380-db6b-11eb-9612-6c0227347444.jpg)

**Comment by JakobStadlhuber** [comment]
Thank you, this is a bug in the web application, we will fix it this weekend. Probably in the night today.

**Comment by JakobStadlhuber** [comment]
Fixed
