### ISSUE TITLE
signature validation enhancement

### ISSUE THREAD

**Issue by KODA-Christian** [GreenPassApp/greenpass-app#32]
Hi, nice work! I'm a huge fan.

Could you help with the signature validation ?

Thanks!

**Comment by JakobStadlhuber** [comment]
Sorry for the late reply, could you please explain your issue in more detail, what is the problem or what exactly do you want?

**Comment by KODA-Christian** [comment]
I was talking about the [// TODO check signature ] in _validateSignature function from CertFetcher class. I am trying to implement this function and I am stuck.

**Comment by kevinhaendel** [comment]
We've already implemented the signature check in ceab444cc8e455eedc825280c66142cb58483b8b, but thank you very much for your helpfulness!
