### ISSUE TITLE
QR codes and PDFs from Finland do not scan and import

### ISSUE THREAD

**Issue by anLizard** [GreenPassApp/greenpass-app#33]
I'm on Android app, version 1.2.0

Nothing happens when trying to scan the QR code from a Finish vaccination certificate.
On the other Austrian app, it works as expected. Sadly I don't really know how to provide more info without handing out the certificate itself.

Please look into it!

**Comment by KODA-Christian** [comment]
I tried the certificates of https://github.com/eu-digital-green-certificates/dcc-quality-assurance/tree/main/FI/1.3.0 . Indeed these certificates cause an exception during the Cose.decodeAndVerify() : ==>Instance of 'ASN1Exception'.
I think the problem comes from the plugin dart_cose itself.

**Comment by kevinhaendel** [comment]
We have noticed that there are problems with Finnish certificates and are currently working on a solution!
