### ISSUE TITLE
PCR test is red but 72h are not over

### ISSUE THREAD

**Issue by reox** [GreenPassApp/greenpass-app#5]
I have added a PCR test via the new PDF import feature.
However the test shows as invalid.
Is this because of a validation issue or because the time for validity is wrongly calculated?
Btw, is it possible to see the signature verification for a token somewhere?

![Screenshot_20210704-112326](https://user-images.githubusercontent.com/431045/124380042-f0fbe580-dcba-11eb-97c2-10feb96f4df9.jpg)

The screenshot shows germany, but same behaviour for .at (i took the screenshot at the wrong time^^)
I checked the qr code with greencheck.gv.at and it shows valid.

Using version 1.0.1 from google play

**Comment by theBest3000** [comment]
Same here. In .at it should be 48h.

![1625420285360](https://user-images.githubusercontent.com/44313069/124394578-532b0980-dd00-11eb-9654-7c60fdaa9e30.jpg)

**Comment by kevinhaendel** [comment]
Thank you for your issue! Could you try to stop and re-launch the app max. two times and look again? Because the app should auto-update the current regulations every day from here: https://github.com/GreenPassApp/shared-data/blob/main/validation-by-country.json

**Comment by ThomasKoppensteiner** [comment]
I have the same situation as @theBest3000. "Selbstest" from a Testzentrum is red after 32 hours (AT ruleset used).
Restarting the app didn't hellp.

**Comment by kevinhaendel** [comment]
Thanks for the issue! Indeed, there was an error when automatically updating the regulations. Will be fixed with the next update!
