### ISSUE TITLE
The testing time is shown in UTC

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [GreenPassApp/greenpass-app#6]
The testing time is 2 hours off.
For example 9:37 is shown instead of 11:37.
I think this 9:37 is in UTC and not in local time.

**Comment by kevinhaendel** [comment]
Could you tell me which app version you are using? You can find the version number in the info page.

**Comment by rulzAT** [comment]
I'm using version 1.0.0 iOS and also having the same issue. 

Its showing my PCR (64h ago) test is not valid. In Austria it should be 72h.

**Comment by ThomasKoppensteiner** [comment]
I'm also using version `1.0.0` on iOS.

**Comment by ThomasKoppensteiner** [comment]
> Its showing my PCR (64h ago) test is not valid. In Austria it should be 72h.

This behaviour fits more to issue #5

**Comment by ThomasKoppensteiner** [comment]
You can compare the result with the "Grüner Pass" app from the BRZ.
There the time displayed in "Datum der Probenahme" is in local time.

**Comment by kevinhaendel** [comment]
This issue was already fixed with app version `1.0.1`. Please wait until the update is available on TestFlight and then try again.

**Comment by ThomasKoppensteiner** [comment]
Waiting for #15 to be able to test this.

**Comment by JakobStadlhuber** [comment]
Fixed and available in the AppStore on iOS or greenpassapp.eu for Android
