### ISSUE TITLE
Certificate Sorting/Grouping/Family Grouping

### ISSUE THREAD

**Issue by hb02** [GreenPassApp/greenpass-app#9]
Nice work.

It would be nice to implement an Option to Sort the Certificates. Eg. I'm currently using my Certificate and the Certificate of my wife. It would be great if i can "Highlight" my Certificate. Maybe it is also possible to Group via Name.

Take a look at the RKI-App https://digitaler-impfnachweis-app.de/ - I will try to upload some sceenshots

![grafik](https://user-images.githubusercontent.com/6522865/124468692-b9179f80-dd99-11eb-8a1b-3fd531ec6fc2.png)
![grafik](https://user-images.githubusercontent.com/6522865/124468722-c3d23480-dd99-11eb-9813-0938295f833c.png)

**Comment by flof93** [comment]
Also an option to hide outdated/not valid certificates would increase the usability a lot.

Right now the Certificates are shown in the order they where added.

**Comment by JakobStadlhuber** [comment]
Just a short update, this will be added in the next version.
